<Project>

  <PropertyGroup>
    <!-- Общие настройки проектов -->
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- На начальном этапе предупреждения не ломают сборку -->
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>

    <!-- Встроенные анализаторы .NET -->
    <AnalysisLevel>10-Recommended</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>

    <!-- IDE-правила пока не проверяются при сборке -->
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Roslynator.Analyzers"
                      PrivateAssets="all"
                      IncludeAssets="runtime;build;native;contentfiles;analyzers;buildtransitive" />

    <PackageReference Include="Meziantou.Analyzer"
                      PrivateAssets="all"
                      IncludeAssets="runtime;build;native;contentfiles;analyzers;buildtransitive" />

    <PackageReference Include="AsyncFixer"
                      PrivateAssets="all"
                      IncludeAssets="runtime;build;native;contentfiles;analyzers;buildtransitive" />

    <PackageReference Include="SonarAnalyzer.CSharp"
                      PrivateAssets="all"
                      IncludeAssets="runtime;build;native;contentfiles;analyzers;buildtransitive" />
  </ItemGroup>

</Project>