<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mnemora.Shared\Mnemora.Shared.csproj" />
    </ItemGroup>

</Project>
