<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationIcon>Assets\Images\Mnemora.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mnemora.Application\Mnemora.Application.csproj"/>
    <ProjectReference Include="..\Mnemora.Contracts\Mnemora.Contracts.csproj"/>
    <ProjectReference Include="..\Mnemora.Infrastructure\Mnemora.Infrastructure.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="MaterialDesignThemes" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Images\Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Images\Mnemora.ico" />
    <Resource Include="Assets\Images\Mnemora.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\MnemoraLogo.png" />
    <None Remove="Assets\Images\MnemoraLogoIcon.png" />
    <Resource Include="Assets\Images\MnemoraLogoIcon.png" />
  </ItemGroup>

</Project>
