// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mnemora.Infrastructure.Persistence;

#nullable disable

namespace Mnemora.Infrastructure.Migrations
{
    [DbContext(typeof(MnemoraDbContext))]
    [Migration("20260905010000_DetachMaterialsFromTopics")]
    partial class DetachMaterialsFromTopics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Mnemora.Domain.LibraryContainers.LibraryContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depth");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2147483647)
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("MNEMORA_UNICODE_NOCASE");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("section_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "SectionId")
                        .HasName("ak_library_containers_id_section_id");

                    b.HasIndex("ParentId", "DisplayOrder")
                        .HasDatabaseName("ix_library_containers_parent_id_display_order");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_library_containers_parent_id_name")
                        .HasFilter("parent_id IS NOT NULL");

                    b.HasIndex("ParentId", "SectionId");

                    b.HasIndex("SectionId", "Depth", "DisplayOrder")
                        .HasDatabaseName("ix_library_containers_section_id_depth_display_order");

                    b.HasIndex(new[] { "SectionId" }, "ux_library_containers_section_id_root")
                        .IsUnique()
                        .HasFilter("parent_id IS NULL");

                    b.ToTable("library_containers", null, t =>
                        {
                            t.HasCheckConstraint("ck_library_containers_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_library_containers_shape", "(parent_id IS NULL AND depth = 0 AND name IS NULL AND color IS NULL AND icon IS NULL) OR (parent_id IS NOT NULL AND depth BETWEEN 1 AND 3 AND name IS NOT NULL AND color IS NOT NULL AND icon IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Mnemora.Domain.Materials.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("container_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("difficulty");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2147483647)
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<int>("LearningRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("learning_revision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .UseCollation("MNEMORA_UNICODE_NOCASE");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("topic_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("ix_materials_container_id");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_materials_topic_id");

                    b.HasIndex("ContainerId", "type")
                        .HasDatabaseName("ix_materials_container_id_type");

                    b.HasIndex("TopicId", "type")
                        .HasDatabaseName("ix_materials_topic_id_type");

                    b.HasIndex("ContainerId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_materials_container_id_created_at_id");

                    b.HasIndex("ContainerId", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_materials_container_id_display_order_id");

                    b.HasIndex("ContainerId", "Title", "Id")
                        .HasDatabaseName("ix_materials_container_id_title_id");

                    b.HasIndex("ContainerId", "UpdatedAt", "Id")
                        .HasDatabaseName("ix_materials_container_id_updated_at_id");

                    b.HasIndex("TopicId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_materials_topic_id_created_at_id");

                    b.HasIndex("TopicId", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_materials_topic_id_display_order_id");

                    b.HasIndex("TopicId", "Title", "Id")
                        .HasDatabaseName("ix_materials_topic_id_title_id");

                    b.HasIndex("TopicId", "UpdatedAt", "Id")
                        .HasDatabaseName("ix_materials_topic_id_updated_at_id");

                    b.ToTable("materials", (string)null);

                    b.HasDiscriminator<int>("type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mnemora.Domain.Sections.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2147483647)
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("MNEMORA_UNICODE_NOCASE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_sections_display_order");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_sections_name");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("Mnemora.Domain.Topics.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2147483647)
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("MNEMORA_UNICODE_NOCASE");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("section_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "DisplayOrder")
                        .HasDatabaseName("ix_topics_section_id_display_order");

                    b.HasIndex("SectionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_topics_section_id_name");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("Mnemora.Domain.Materials.Article", b =>
                {
                    b.HasBaseType("Mnemora.Domain.Materials.Material");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Mnemora.Domain.Materials.Question", b =>
                {
                    b.HasBaseType("Mnemora.Domain.Materials.Material");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("article_id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_materials_article_id");

                    b.HasIndex("TopicId", "ArticleId")
                        .HasDatabaseName("ix_materials_topic_id_article_id");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Mnemora.Domain.LibraryContainers.LibraryContainer", b =>
                {
                    b.HasOne("Mnemora.Domain.Sections.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mnemora.Domain.LibraryContainers.LibraryContainer", null)
                        .WithMany()
                        .HasForeignKey("ParentId", "SectionId")
                        .HasPrincipalKey("Id", "SectionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mnemora.Domain.Materials.Material", b =>
                {
                    b.HasOne("Mnemora.Domain.LibraryContainers.LibraryContainer", null)
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Mnemora.Domain.Materials.MaterialExperienceRewards", "ExperienceRewards", b1 =>
                        {
                            b1.Property<Guid>("MaterialId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ReviewPoints")
                                .HasColumnType("INTEGER")
                                .HasColumnName("review_points");

                            b1.Property<int>("StudyPoints")
                                .HasColumnType("INTEGER")
                                .HasColumnName("study_points");

                            b1.HasKey("MaterialId");

                            b1.ToTable("materials");

                            b1.WithOwner()
                                .HasForeignKey("MaterialId");
                        });

                    b.OwnsMany("Mnemora.Domain.Materials.MaterialTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("material_id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("value")
                                .UseCollation("MNEMORA_UNICODE_NOCASE");

                            b1.HasKey("material_id", "Value");

                            b1.HasIndex("Value")
                                .HasDatabaseName("ix_material_tags_value");

                            b1.ToTable("material_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("material_id");
                        });

                    b.Navigation("ExperienceRewards")
                        .IsRequired();

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Mnemora.Domain.Topics.Topic", b =>
                {
                    b.HasOne("Mnemora.Domain.Sections.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mnemora.Domain.Materials.Question", b =>
                {
                    b.HasOne("Mnemora.Domain.Materials.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
