<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Mnemora.Contracts\Mnemora.Contracts.csproj" />
      <ProjectReference Include="..\Mnemora.Domain\Mnemora.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Home\" />
    </ItemGroup>

</Project>
